"""initial schema
Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-24
"""
from alembic import op
import sqlalchemy as sa
revision = "0001_initial"; down_revision = None; branch_labels = None; depends_on = None

def upgrade():
    op.create_table('users', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('telegram_id', sa.BigInteger(), nullable=False), sa.Column('username', sa.String(255)), sa.Column('first_name', sa.String(255)), sa.Column('city', sa.String(120), server_default='Москва', nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('places', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('provider', sa.String(50), nullable=False), sa.Column('external_id', sa.String(255), nullable=False), sa.Column('name', sa.String(255), nullable=False), sa.Column('category', sa.String(50), nullable=False), sa.Column('city', sa.String(120), server_default='Москва', nullable=False), sa.Column('address', sa.String(500)), sa.Column('description', sa.Text()), sa.Column('lat', sa.Float()), sa.Column('lon', sa.Float()), sa.Column('rating', sa.Float()), sa.Column('phone', sa.String(80)), sa.Column('website', sa.String(500)), sa.Column('working_hours', sa.String(255)), sa.Column('source_url', sa.String(500)), sa.UniqueConstraint('provider','external_id', name='uq_place_provider_external'))
    op.create_index(op.f('ix_places_category'), 'places', ['category']); op.create_index(op.f('ix_places_city'), 'places', ['city'])
    op.create_table('settings', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False), sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column('radius_km', sa.Integer(), server_default='5', nullable=False), sa.Column('language', sa.String(10), server_default='ru', nullable=False), sa.UniqueConstraint('user_id'))
    op.create_table('favorites', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False), sa.Column('place_id', sa.Integer(), sa.ForeignKey('places.id', ondelete='CASCADE'), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint('user_id','place_id', name='uq_favorite_user_place'))
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'])

    op.create_table('reviews', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False), sa.Column('place_id', sa.Integer(), sa.ForeignKey('places.id', ondelete='CASCADE'), nullable=False), sa.Column('rating', sa.Integer(), nullable=False), sa.Column('text', sa.Text()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint('user_id','place_id', name='uq_review_user_place'))
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id']); op.create_index(op.f('ix_reviews_place_id'), 'reviews', ['place_id'])
    op.create_table('ad_campaigns', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False), sa.Column('place_id', sa.Integer(), sa.ForeignKey('places.id', ondelete='CASCADE'), nullable=False), sa.Column('tariff_code', sa.String(30), nullable=False), sa.Column('status', sa.String(30), nullable=False), sa.Column('priority', sa.Integer(), nullable=False), sa.Column('stars_paid', sa.Integer(), nullable=False), sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index(op.f('ix_ad_campaigns_user_id'), 'ad_campaigns', ['user_id']); op.create_index(op.f('ix_ad_campaigns_place_id'), 'ad_campaigns', ['place_id']); op.create_index(op.f('ix_ad_campaigns_status'), 'ad_campaigns', ['status']); op.create_index(op.f('ix_ad_campaigns_ends_at'), 'ad_campaigns', ['ends_at'])
    op.create_table('ad_payments', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False), sa.Column('place_id', sa.Integer(), sa.ForeignKey('places.id', ondelete='CASCADE'), nullable=False), sa.Column('tariff_code', sa.String(30), nullable=False), sa.Column('stars_amount', sa.Integer(), nullable=False), sa.Column('telegram_payment_charge_id', sa.String(255)), sa.Column('provider_payment_charge_id', sa.String(255)), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index(op.f('ix_ad_payments_user_id'), 'ad_payments', ['user_id']); op.create_index(op.f('ix_ad_payments_place_id'), 'ad_payments', ['place_id'])
    op.create_table('search_history', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False), sa.Column('query_type', sa.String(50), nullable=False), sa.Column('city', sa.String(120)), sa.Column('lat', sa.Float()), sa.Column('lon', sa.Float()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id']); op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'])

def downgrade():
    op.drop_table('search_history'); op.drop_table('ad_payments'); op.drop_table('ad_campaigns'); op.drop_table('reviews'); op.drop_table('favorites'); op.drop_table('settings'); op.drop_index(op.f('ix_places_city'), table_name='places'); op.drop_index(op.f('ix_places_category'), table_name='places'); op.drop_table('places'); op.drop_index(op.f('ix_users_telegram_id'), table_name='users'); op.drop_table('users')
